import type { VonderaProduct, VonderaCategory, VonderaStore } from '@/types';

export const mockStore: VonderaStore = {
  id: 'demo-store',
  name: 'VONDERA',
  logo: '',
  slogan: 'Live outside boundaries',
  country: 'US',
  currency: 'USD',
  domains: ['https://vondera.local'],
  social: {
    phone: '+1 (555) 123-4567',
    instagram: 'https://instagram.com/vondera',
    facebook: 'https://facebook.com/vondera',
  },
  zones: [
    { id: 'z1', name: 'Standard Shipping', fees: 8, enabled: true, estimatedDeliveryTimeInDays: 5 },
    { id: 'z2', name: 'Express Shipping', fees: 18, enabled: true, estimatedDeliveryTimeInDays: 2 },
  ],
};

export const mockCategories: VonderaCategory[] = [
  {
    id: 'cat-outerwear',
    name: 'Outerwear',
    description: 'Timeless coats and jackets for every season',
    image: '/category-outerwear.jpg',
    link: '/shop?category=outerwear',
    subCategories: [],
    productsCount: 12,
  },
  {
    id: 'cat-knitwear',
    name: 'Knitwear',
    description: 'Hand-finished sweaters and cardigans',
    image: '/category-knitwear.jpg',
    link: '/shop?category=knitwear',
    subCategories: [],
    productsCount: 10,
  },
  {
    id: 'cat-accessories',
    name: 'Accessories',
    description: 'Bags, scarves, and leather goods',
    image: '/category-accessories.jpg',
    link: '/shop?category=accessories',
    subCategories: [],
    productsCount: 8,
  },
  {
    id: 'cat-trousers',
    name: 'Trousers',
    description: 'Tailored and relaxed pants',
    image: '/category-knitwear.jpg',
    link: '/shop?category=trousers',
    subCategories: [],
    productsCount: 6,
  },
];

export const mockProducts: VonderaProduct[] = [
  {
    id: 'prod-1',
    name: 'Linen Overshirt',
    description: 'Cut from premium European linen with a relaxed, unstructured fit. Features a camp collar, mother-of-pearl buttons, and a curved hem designed to be worn untucked. Softens beautifully with each wash.',
    price: 145,
    mainImage: { small: '/product-1.jpg', large: '/product-1.jpg' },
    images: ['/product-1.jpg'],
    link: '/product/prod-1',
    categoryName: 'Outerwear',
    categoryId: 'cat-outerwear',
    isAvailable: true,
    currency: 'USD',
    country: 'US',
    quantity: 50,
    variants: { Color: ['Olive', 'Sand', 'Charcoal'], Size: ['S', 'M', 'L', 'XL'] },
    variantsDisplay: { Color: ['Olive', 'Sand', 'Charcoal'], Size: ['S', 'M', 'L', 'XL'] },
    variantsSettings: [
      { id: 'v1-1', quantity: 15, price: 145, sku: 'LIN-OL-S', displayOptions: { Color: 'Olive', Size: 'S' }, currency: 'USD', country: 'US' },
      { id: 'v1-2', quantity: 15, price: 145, sku: 'LIN-OL-M', displayOptions: { Color: 'Olive', Size: 'M' }, currency: 'USD', country: 'US' },
      { id: 'v1-3', quantity: 10, price: 145, sku: 'LIN-OL-L', displayOptions: { Color: 'Olive', Size: 'L' }, currency: 'USD', country: 'US' },
      { id: 'v1-4', quantity: 10, price: 145, sku: 'LIN-SN-M', displayOptions: { Color: 'Sand', Size: 'M' }, currency: 'USD', country: 'US' },
    ],
    rating: { average: 4.8, count: 24 },
    labels: { lastPiece: false, outOfStock: false },
  },
  {
    id: 'prod-2',
    name: 'Wool Wide Trousers',
    description: 'Crafted from Italian merino wool with a fluid drape and generous cut. Features a clean waistband with concealed fastening and deep side pockets.',
    price: 195,
    mainImage: { small: '/product-2.jpg', large: '/product-2.jpg' },
    images: ['/product-2.jpg'],
    link: '/product/prod-2',
    categoryName: 'Trousers',
    categoryId: 'cat-trousers',
    isAvailable: true,
    currency: 'USD',
    country: 'US',
    quantity: 30,
    variants: { Color: ['Taupe', 'Charcoal'], Size: ['S', 'M', 'L', 'XL'] },
    variantsDisplay: { Color: ['Taupe', 'Charcoal'], Size: ['S', 'M', 'L', 'XL'] },
    variantsSettings: [
      { id: 'v2-1', quantity: 10, price: 195, sku: 'WTR-TA-M', displayOptions: { Color: 'Taupe', Size: 'M' }, currency: 'USD', country: 'US' },
      { id: 'v2-2', quantity: 10, price: 195, sku: 'WTR-TA-L', displayOptions: { Color: 'Taupe', Size: 'L' }, currency: 'USD', country: 'US' },
    ],
    rating: { average: 4.6, count: 18 },
    labels: { lastPiece: false, outOfStock: false },
  },
  {
    id: 'prod-3',
    name: 'Cable Knit Sweater',
    description: 'Hand-knitted in small batches from Scottish lambswool. The intricate cable pattern adds texture and warmth, while the relaxed fit layers effortlessly over shirts.',
    price: 245,
    mainImage: { small: '/product-3.jpg', large: '/product-3.jpg' },
    images: ['/product-3.jpg'],
    link: '/product/prod-3',
    categoryName: 'Knitwear',
    categoryId: 'cat-knitwear',
    isAvailable: true,
    currency: 'USD',
    country: 'US',
    quantity: 20,
    variants: { Color: ['Cream', 'Oatmeal'], Size: ['S', 'M', 'L'] },
    variantsDisplay: { Color: ['Cream', 'Oatmeal'], Size: ['S', 'M', 'L'] },
    variantsSettings: [
      { id: 'v3-1', quantity: 8, price: 245, sku: 'CBL-CR-S', displayOptions: { Color: 'Cream', Size: 'S' }, currency: 'USD', country: 'US' },
      { id: 'v3-2', quantity: 7, price: 245, sku: 'CBL-CR-M', displayOptions: { Color: 'Cream', Size: 'M' }, currency: 'USD', country: 'US' },
      { id: 'v3-3', quantity: 5, price: 245, sku: 'CBL-OT-L', displayOptions: { Color: 'Oatmeal', Size: 'L' }, currency: 'USD', country: 'US' },
    ],
    rating: { average: 4.9, count: 32 },
    labels: { lastPiece: false, outOfStock: false },
  },
  {
    id: 'prod-4',
    name: 'Canvas Field Tote',
    description: 'A generous carryall in heavyweight raw cotton canvas with vegetable-tanned leather handles. Reinforced base and interior pocket. Ages beautifully with use.',
    price: 125,
    mainImage: { small: '/product-4.jpg', large: '/product-4.jpg' },
    images: ['/product-4.jpg'],
    link: '/product/prod-4',
    categoryName: 'Accessories',
    categoryId: 'cat-accessories',
    isAvailable: true,
    currency: 'USD',
    country: 'US',
    quantity: 40,
    variants: {},
    variantsDisplay: {},
    variantsSettings: [],
    rating: { average: 4.7, count: 15 },
    labels: { lastPiece: false, outOfStock: false },
  },
  {
    id: 'prod-5',
    name: 'Denim Chore Jacket',
    description: 'A workwear-inspired jacket in 12oz Japanese selvedge denim. Cut for an easy, boxy fit with patch pockets and corozo buttons. Washes down to a soft, personal blue.',
    price: 175,
    mainImage: { small: '/product-5.jpg', large: '/product-5.jpg' },
    images: ['/product-5.jpg'],
    link: '/product/prod-5',
    categoryName: 'Outerwear',
    categoryId: 'cat-outerwear',
    isAvailable: true,
    currency: 'USD',
    country: 'US',
    quantity: 25,
    variants: { Size: ['S', 'M', 'L', 'XL'] },
    variantsDisplay: { Size: ['S', 'M', 'L', 'XL'] },
    variantsSettings: [
      { id: 'v5-1', quantity: 8, price: 175, sku: 'DEN-S', displayOptions: { Size: 'S' }, currency: 'USD', country: 'US' },
      { id: 'v5-2', quantity: 7, price: 175, sku: 'DEN-M', displayOptions: { Size: 'M' }, currency: 'USD', country: 'US' },
      { id: 'v5-3', quantity: 6, price: 175, sku: 'DEN-L', displayOptions: { Size: 'L' }, currency: 'USD', country: 'US' },
      { id: 'v5-4', quantity: 4, price: 175, sku: 'DEN-XL', displayOptions: { Size: 'XL' }, currency: 'USD', country: 'US' },
    ],
    rating: { average: 4.5, count: 21 },
    labels: { lastPiece: false, outOfStock: false },
  },
  {
    id: 'prod-6',
    name: 'Cashmere Wrap Scarf',
    description: 'Woven from grade-A Mongolian cashmere with a feather-light hand. Generous dimensions allow for multiple styling options. Finished with hand-rolled edges.',
    price: 165,
    mainImage: { small: '/product-6.jpg', large: '/product-6.jpg' },
    images: ['/product-6.jpg'],
    link: '/product/prod-6',
    categoryName: 'Accessories',
    categoryId: 'cat-accessories',
    isAvailable: true,
    currency: 'USD',
    country: 'US',
    quantity: 35,
    variants: { Color: ['Burgundy', 'Charcoal', 'Cream'] },
    variantsDisplay: { Color: ['Burgundy', 'Charcoal', 'Cream'] },
    variantsSettings: [
      { id: 'v6-1', quantity: 15, price: 165, sku: 'CSH-BG', displayOptions: { Color: 'Burgundy' }, currency: 'USD', country: 'US' },
      { id: 'v6-2', quantity: 12, price: 165, sku: 'CSH-CH', displayOptions: { Color: 'Charcoal' }, currency: 'USD', country: 'US' },
      { id: 'v6-3', quantity: 8, price: 165, sku: 'CSH-CR', displayOptions: { Color: 'Cream' }, currency: 'USD', country: 'US' },
    ],
    rating: { average: 4.8, count: 28 },
    labels: { lastPiece: false, outOfStock: false },
  },
  {
    id: 'prod-7',
    name: 'Merino Turtleneck',
    description: 'A refined essential in extra-fine merino wool. Slim but not tight, with a substantial ribbed collar that sits perfectly. Machine washable.',
    price: 135,
    mainImage: { small: '/product-3.jpg', large: '/product-3.jpg' },
    images: ['/product-3.jpg'],
    link: '/product/prod-7',
    categoryName: 'Knitwear',
    categoryId: 'cat-knitwear',
    isAvailable: true,
    currency: 'USD',
    country: 'US',
    quantity: 45,
    variants: { Color: ['Black', 'Charcoal', 'Ivory'], Size: ['S', 'M', 'L', 'XL'] },
    variantsDisplay: { Color: ['Black', 'Charcoal', 'Ivory'], Size: ['S', 'M', 'L', 'XL'] },
    variantsSettings: [
      { id: 'v7-1', quantity: 15, price: 135, sku: 'MER-BK-M', displayOptions: { Color: 'Black', Size: 'M' }, currency: 'USD', country: 'US' },
      { id: 'v7-2', quantity: 15, price: 135, sku: 'MER-IV-L', displayOptions: { Color: 'Ivory', Size: 'L' }, currency: 'USD', country: 'US' },
    ],
    rating: { average: 4.4, count: 12 },
    labels: { lastPiece: false, outOfStock: false },
  },
  {
    id: 'prod-8',
    name: 'Waxed Cotton Parka',
    description: 'Built for the elements in British Millerain waxed cotton. Features a storm hood, snap placket, and warm brushed-cotton lining. Develops a unique patina over time.',
    price: 295,
    mainImage: { small: '/product-5.jpg', large: '/product-5.jpg' },
    images: ['/product-5.jpg'],
    link: '/product/prod-8',
    categoryName: 'Outerwear',
    categoryId: 'cat-outerwear',
    isAvailable: true,
    currency: 'USD',
    country: 'US',
    quantity: 15,
    variants: { Color: ['Olive', 'Navy'], Size: ['S', 'M', 'L', 'XL'] },
    variantsDisplay: { Color: ['Olive', 'Navy'], Size: ['S', 'M', 'L', 'XL'] },
    variantsSettings: [
      { id: 'v8-1', quantity: 8, price: 295, sku: 'PARK-OL-M', displayOptions: { Color: 'Olive', Size: 'M' }, currency: 'USD', country: 'US' },
    ],
    rating: { average: 4.9, count: 9 },
    labels: { lastPiece: false, outOfStock: false },
  },
  {
    id: 'prod-9',
    name: 'Leather Belt',
    description: 'Hand-cut from full-grain vegetable-tanned leather. Solid brass buckle with a matte finish. Width: 3.5cm. Made to last decades.',
    price: 85,
    mainImage: { small: '/product-4.jpg', large: '/product-4.jpg' },
    images: ['/product-4.jpg'],
    link: '/product/prod-9',
    categoryName: 'Accessories',
    categoryId: 'cat-accessories',
    isAvailable: true,
    currency: 'USD',
    country: 'US',
    quantity: 60,
    variants: { Color: ['Tan', 'Black', 'Brown'] },
    variantsDisplay: { Color: ['Tan', 'Black', 'Brown'] },
    variantsSettings: [
      { id: 'v9-1', quantity: 20, price: 85, sku: 'BLT-TN', displayOptions: { Color: 'Tan' }, currency: 'USD', country: 'US' },
      { id: 'v9-2', quantity: 20, price: 85, sku: 'BLT-BK', displayOptions: { Color: 'Black' }, currency: 'USD', country: 'US' },
      { id: 'v9-3', quantity: 20, price: 85, sku: 'BLT-BR', displayOptions: { Color: 'Brown' }, currency: 'USD', country: 'US' },
    ],
    rating: { average: 4.6, count: 14 },
    labels: { lastPiece: false, outOfStock: false },
  },
  {
    id: 'prod-10',
    name: 'Pleated Wool Trousers',
    description: 'Italian virgin wool with permanent creases and a flattering high rise. Tapered leg that breaks cleanly over shoes. Partially lined for comfort.',
    price: 215,
    mainImage: { small: '/product-2.jpg', large: '/product-2.jpg' },
    images: ['/product-2.jpg'],
    link: '/product/prod-10',
    categoryName: 'Trousers',
    categoryId: 'cat-trousers',
    isAvailable: true,
    currency: 'USD',
    country: 'US',
    quantity: 20,
    variants: { Color: ['Charcoal', 'Navy'], Size: ['S', 'M', 'L', 'XL'] },
    variantsDisplay: { Color: ['Charcoal', 'Navy'], Size: ['S', 'M', 'L', 'XL'] },
    variantsSettings: [
      { id: 'v10-1', quantity: 10, price: 215, sku: 'PLT-CH-M', displayOptions: { Color: 'Charcoal', Size: 'M' }, currency: 'USD', country: 'US' },
    ],
    rating: { average: 4.7, count: 11 },
    labels: { lastPiece: false, outOfStock: false },
  },
  {
    id: 'prod-11',
    name: 'Alpaca Cardigan',
    description: 'Knitted from baby alpaca for unmatched softness and warmth. The shawl collar and horn buttons elevate a casual silhouette to something special.',
    price: 275,
    mainImage: { small: '/product-3.jpg', large: '/product-3.jpg' },
    images: ['/product-3.jpg'],
    link: '/product/prod-11',
    categoryName: 'Knitwear',
    categoryId: 'cat-knitwear',
    isAvailable: true,
    currency: 'USD',
    country: 'US',
    quantity: 12,
    variants: { Color: ['Moss', 'Rust'], Size: ['S', 'M', 'L'] },
    variantsDisplay: { Color: ['Moss', 'Rust'], Size: ['S', 'M', 'L'] },
    variantsSettings: [
      { id: 'v11-1', quantity: 6, price: 275, sku: 'ALP-MO-M', displayOptions: { Color: 'Moss', Size: 'M' }, currency: 'USD', country: 'US' },
    ],
    rating: { average: 5.0, count: 7 },
    labels: { lastPiece: false, outOfStock: false },
  },
  {
    id: 'prod-12',
    name: 'Shearling Collar Coat',
    description: 'A statement piece in heavy melton wool with a genuine shearling collar. Double-breasted with authentic horn buttons. Fully lined in satin.',
    price: 395,
    mainImage: { small: '/product-1.jpg', large: '/product-1.jpg' },
    images: ['/product-1.jpg'],
    link: '/product/prod-12',
    categoryName: 'Outerwear',
    categoryId: 'cat-outerwear',
    isAvailable: true,
    currency: 'USD',
    country: 'US',
    quantity: 8,
    variants: { Color: ['Camel', 'Black'], Size: ['S', 'M', 'L'] },
    variantsDisplay: { Color: ['Camel', 'Black'], Size: ['S', 'M', 'L'] },
    variantsSettings: [
      { id: 'v12-1', quantity: 4, price: 395, sku: 'SHR-CA-M', displayOptions: { Color: 'Camel', Size: 'M' }, currency: 'USD', country: 'US' },
    ],
    rating: { average: 4.8, count: 5 },
    labels: { lastPiece: true, outOfStock: false },
  },
];

export function getMockProducts(pageNo: number, limit: number, categoryId?: string): { items: VonderaProduct[]; isLastPage: boolean; nextPageNumber: number | null; currentPage: number; totalPages: number } {
  let filtered = mockProducts;
  if (categoryId) {
    filtered = mockProducts.filter(p => p.categoryId === categoryId);
  }
  const totalPages = Math.ceil(filtered.length / limit);
  const start = (pageNo - 1) * limit;
  const items = filtered.slice(start, start + limit);
  return {
    items,
    isLastPage: pageNo >= totalPages,
    nextPageNumber: pageNo < totalPages ? pageNo + 1 : null,
    currentPage: pageNo,
    totalPages,
  };
}

export function getMockProductById(id: string): VonderaProduct | undefined {
  return mockProducts.find(p => p.id === id);
}

export function getMockCategories(): VonderaCategory[] {
  return mockCategories;
}

export function getMockStore(): VonderaStore {
  return mockStore;
}
